server:
  port: 8081

#配置数据库连接信息
spring:
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.38:3306/20066
    username: root
    password: root
  data:
    mongodb:
      uri: mongodb://192.168.1.38:27017/2006
mybatis:
  #mybatisxml文件的地址
  mapper-locations: classpath:mapper/*.xml
  #showsql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
